openapi: 3.0.0

x-amazon-apigateway-request-validators:
  basic:
    validateRequestBody: false
    validateRequestParameters: true

x-amazon-apigateway-request-validator: basic
paths:
  /users:
    get:
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: integer
        - in: query
          name: user_name
          required: false
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:get-user-lambda/invocations"
        httpMethod: "POST"

  /users/{user_name}:
    get:
      parameters:
        - in: path
          name: user_name
          required: false
          schema:
            type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:get-user-lambda2/invocations"
        httpMethod: "POST"